### ISSUE TITLE
Broken URL/link in README.md for "Template: Windows - Simple Windows install"

### ISSUE THREAD

**Issue by i27i13** [xn0px90/Awesome-Qubes-OS#14]
Hello :)

In:
https://github.com/xn0px90/awesome-qubes-os/blob/main/README.md

The link for:
Template: Windows - Simple Windows install
https://github.com/Qubes-Community/Contents/blob/master/docs/os/windows/windows-vm.md

no longer works:
"This content was removed as part of the migration to Qubes Forum: Community Guides. Learn more."

**Comment by xn0px90** [comment]
thanks!!!
